### ISSUE TITLE
Failure to find database table

### ISSUE THREAD

**Issue by infojunkie** [djezzzl/database_consistency#21]
Your tool looks perfect for our purpose of finding data inconsistencies - thanks! However, when I run it, I get the following error:
```
root@8b06bb2b49e8:/app# bundle exec database_consistency
Thank you for using the gem. Any contribution is welcome https://github.com/djezzzl/database_consistency!
(c) Evgeniy Demin <lawliet.djez@gmail.com>

/var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::UndefinedTable: ERROR:  relation "version_associations" does not exist (ActiveRecord::StatementInvalid)
LINE 5:                WHERE a.attrelid = '"version_associations"'::...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"version_associations"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql/schema_statements.rb:197:in `columns'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/attributes.rb:93:in `columns'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/columns_processor.rb:15:in `block in check'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/columns_processor.rb:14:in `each'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/columns_processor.rb:14:in `flat_map'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/columns_processor.rb:14:in `check'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/base_processor.rb:27:in `reports'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/base_processor.rb:12:in `block in reports'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/base_processor.rb:11:in `each'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/base_processor.rb:11:in `flat_map'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency/processors/base_processor.rb:11:in `reports'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/lib/database_consistency.rb:34:in `run'
	from /var/lib/gems/2.3.0/gems/database_consistency-0.6.6/bin/database_consistency:30:in `<top (required)>'
	from /usr/local/bin/database_consistency:22:in `load'
	from /usr/local/bin/database_consistency:22:in `<main>'
```
Examining the existing parent models, I see:
```
irb(main):008:0> ActiveRecord::Base.descendants.delete_if(&:abstract_class?).join(", ")
=> "DynamicAnnotation::Field, Dynamic, PaperTrail::Version, Bot::Viber, ProjectMedia, Bot::BridgeReader, Team, TeamTask, Task, Comment, Media, Bot::Slack, Embed, TeamUser, Project, Tag, Flag, Assignment, DynamicAnnotation::AnnotationType, ProjectSource, User, PaperTrail::VersionAssociation, Account, AccountSource, Annotation, ApiKey, Bot::Alegre, Bot::Bot, Bot::Facebook, Relationship, Bot::Twitter, Bounce, ClaimSource, Contact, DynamicAnnotation::FieldInstance, DynamicAnnotation::FieldType, Source, TagText, TeamBot, TeamBotInstallation, UploadedFile, Claim, Link, UploadedImage, BotUser"
```
which includes `PaperTrail::VersionAssociation` that the failure above is complaining about. However, this model is added by a 3rd-party gem and I would hate to debug through _their_ code to find what's wrong. Would it make sense to add a config to exclude some models?

**Comment by djezzzl** [comment]
Hi @infojunkie, thank you for bringing this. 

Could you please try to configure it as described [here](https://github.com/djezzzl/database_consistency/blob/master/rails-example/.database_consistency.yml). 

In your case, adding
```
'PaperTrail::VersionAssociation':
  enabled: false
```
should help. Please let me know if it doesn't 👍

**Comment by djezzzl** [comment]
I'll close issue for now because I think the solution above should help.

**Comment by infojunkie** [comment]
Thanks for your response. Unfortunately, the crash is still happening. Looking at the stack trace, the crash occurs within ActiveRecord itself, when `ColumnsProcessor` lists the columns of the model at https://github.com/djezzzl/database_consistency/blob/38c3b2825c55cd9164d25dc2f6f12639e87115c5/lib/database_consistency/processors/columns_processor.rb#L15, even before it checks for the `enabled` flag. 

Going deeper, it seems the class in question `PaperTrail::VersionAssociation` is auto-created by ActiveRecord, given my attempt to locate its source location:
```
irb(main):004:0> PaperTrail::VersionAssociation.instance_methods(false).map { |m| 
irb(main):005:1*   PaperTrail::VersionAssociation.instance_method(m).source_location.first
irb(main):006:1> }.uniq
=> ["/var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/associations/builder/belongs_to.rb", "/var/lib/gems/2.3.0/gems/activerecord-4.2.11/lib/active_record/autosave_association.rb"]
```

I don't know what ActiveRecord is doing exactly in this case, but it looks like this model is synthetic and is not expected to have its own table.

**Comment by djezzzl** [comment]
Thank you @infojunkie, you're right. Could you please try latest version (0.6.7). Should be fixed there. https://github.com/djezzzl/database_consistency/commit/c7025bb3a50cbf0676c445966f5b4a86c4ce183f

**Comment by infojunkie** [comment]
Thanks, the crash no longer occurs :pray:
