### ISSUE TITLE
RedundantIndexChecker autofix create incorrect migration

### ISSUE THREAD

**Issue by ducmanh2111** [djezzzl/database_consistency#231]
Due to the lack of table_name and column for `RedundantIndexChecker`, the migration generated from autofix writer was incorrect.

**Given**
Step 1: I ran `bundle exec database_consistency` and it received:
![image](https://github.com/user-attachments/assets/6f23fd72-5a03-49be-b463-0e08a22a2ae6)
Step 2: I ran `bundle exec database_consistency -f` and it created a migration to fix the check:
```ruby
class RemoveIndexInvoiceNotesOnInvoiceIdIndex < ActiveRecord::Migration[6.1]
  def change
    remove_index nil, name: 'index_invoice_notes_on_invoice_id'
  end
end
```
**When**
I ran `bundle exec rails db:migrate`

**Then**
```ruby
== 20240823165209 RemoveIndexInvoiceNotesOnInvoiceIdIndex: migrating ==========
-- remove_index(nil, {:name=>"index_invoice_notes_on_invoice_id"})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Incorrect table name ''
/myapp/db/migrate/20240823165209_remove_index_invoice_notes_on_invoice_id_index.rb:3:in `change'
/myapp/bin/rails:5:in `<top (required)>'
/myapp/bin/spring:10:in `block in <top (required)>'
/myapp/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect table name ''
/myapp/db/migrate/20240823165209_remove_index_invoice_notes_on_invoice_id_index.rb:3:in `change'
/myapp/bin/rails:5:in `<top (required)>'
/myapp/bin/spring:10:in `block in <top (required)>'
/myapp/bin/spring:7:in `<top (required)>'

Caused by:
Mysql2::Error: Incorrect table name ''
/myapp/db/migrate/20240823165209_remove_index_invoice_notes_on_invoice_id_index.rb:3:in `change'
/myapp/bin/rails:5:in `<top (required)>'
/myapp/bin/spring:10:in `block in <top (required)>'
/myapp/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
**Expected Output**
```ruby
class RemoveIndexInvoiceNotesOnInvoiceIdIndex < ActiveRecord::Migration[6.1]
  def change
    remove_index :invoice_notes, name: 'index_invoice_notes_on_invoice_id', column: :invoice_id
  end
end
```

**Comment by djezzzl** [comment]
Hi @ducmanh2111,

Thank you for pointing this out! 
It should be fixed in the next release: https://github.com/djezzzl/database_consistency/pull/243

Thank you!
