### ISSUE TITLE
Checks fail with error due to association to non-existing model/table

### ISSUE THREAD

**Issue by matthieugendreau** [djezzzl/database_consistency#30]
Hi,

I am using version 0.7.1 and `bundle exec database_consistency` is generating an error report that looks like this:

```
<===begin===>
Traceback (most recent call last):
	26: from /home/matthieu/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	25: from /home/matthieu/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	24: from /home/matthieu/.rvm/gems/ruby-2.6.0/bin/database_consistency:23:in `<main>'
	23: from /home/matthieu/.rvm/gems/ruby-2.6.0/bin/database_consistency:23:in `load'
	22: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/bin/database_consistency:26:in `<top (required)>'
	21: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency.rb:34:in `run'
	20: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/base_processor.rb:11:in `reports'
	19: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/base_processor.rb:11:in `flat_map'
	18: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/base_processor.rb:11:in `each'
	17: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/base_processor.rb:12:in `block in reports'
	16: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/base_processor.rb:27:in `reports'
	15: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:14:in `check'
	14: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:14:in `flat_map'
	13: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:14:in `each'
	12: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:17:in `block in check'
	11: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:17:in `flat_map'
	10: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:17:in `each'
	 9: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:18:in `block (2 levels) in check'
	 8: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:18:in `map'
	 7: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/processors/associations_processor.rb:20:in `block (3 levels) in check'
	 6: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/checkers/base_checker.rb:30:in `report_if_enabled?'
	 5: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/checkers/base_checker.rb:23:in `report'
	 4: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/checkers/association_checkers/missing_index_checker.rb:28:in `check'
	 3: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/database_consistency-0.7.1/lib/database_consistency/checkers/association_checkers/missing_index_checker.rb:36:in `index'
	 2: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.2.1/lib/active_record/reflection.rb:379:in `klass'
	 1: from /home/matthieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.2.1/lib/active_record/reflection.rb:422:in `compute_class'
/home/matthieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.2.1/lib/active_record/inheritance.rb:196:in `compute_type': uninitialized constant User::OldTable (NameError)
<===end===>
```

The source of the error is because I have an association is the user model to a model that has been deleted since (`has_one :old_table, dependent: :restrict_with_exception`).

Also would it be possible to return an exit code 1 when some checks fail with an error? I am currently using the gem as part of my automated tests on Travis and I won't necessarily see the error if the build returns 0.

Thanks for everything, the gem has been really helpful to me so far!

**Comment by djezzzl** [comment]
Hey, thank you for pointing this out!

Your both requests are addressed in https://github.com/djezzzl/database_consistency/pull/31:
- Ignore `MissingIndexChecker` when there is no associated model
- Exit with fail if some error occurs (so you can detect it on CI)

Please, update gem to latest version: `0.7.2`.

**Comment by matthieugendreau** [comment]
Perfect thanks a lot!
