### ISSUE TITLE
Install success despite using Invalid Ruby 2.3.7 Version

### ISSUE THREAD

**Issue by EEtancelin** [djezzzl/database_consistency#34]
Sorry for the telegraphic style, following guess was the best way to be clear.

### When we : 
run ```bundle exec database_consistency``` on ruby 2.3.7
### We got : an Error

```Did you mean?  match ```  

### Because 
 match? have been introduce in 2.4.0

### I was expecting : 
An error at install time . As this version is not compatible and Ruby 2.3.7, [is not supported anymore](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/). 

### Here the backtrace : 
```
Did you mean?  match
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/configuration.rb:20:in `debug?'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/writers/base_writer.rb:15:in `write?'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/writers/simple_writer.rb:17:in `block in write'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/writers/simple_writer.rb:16:in `each'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/writers/simple_writer.rb:16:in `write'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency/writers/base_writer.rb:19:in `write'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/lib/database_consistency.rb:36:in `run'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/database_consistency-0.7.3/bin/database_consistency:26:in `<top (required)>'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/bin/database_consistency:22:in `load'
  /Users/edouardetancelin/.rbenv/versions/2.3.7/bin/database_consistency:22:in `<top (required)>'
```

**Comment by djezzzl** [comment]
Thank you 👍  PR is merged.
