### ISSUE TITLE
Error in v 0.8.8

### ISSUE THREAD

**Issue by uxxman** [djezzzl/database_consistency#71]
Rails: 6.0.3.4
Postgres: 12.4

```
<===begin===>
[1mTraceback[m (most recent call last):
	39: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	38: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	37: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	36: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	35: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	34: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
	33: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	32: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	31: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	30: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	29: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	28: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:476:in `exec'
	27: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	26: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	25: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	24: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `<top (required)>'
	23: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `load'
	22: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/bin/database_consistency:44:in `<top (required)>'
	21: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency.rb:47:in `run'
	20: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	19: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	18: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `each'
	17: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	16: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	15: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	14: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	13: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	12: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	11: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	10: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 9: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 8: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 7: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 6: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 5: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 4: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 3: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
	 2: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:71:in `associated_key'
	 1: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:472:in `active_record_primary_key'
/Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:322:in `primary_key': [1mUnknown primary key for table favorites in model Favorite. ([1;4mActiveRecord::UnknownPrimaryKey[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	39: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	38: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	37: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	36: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	35: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	34: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
	33: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	32: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	31: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	30: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	29: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	28: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:476:in `exec'
	27: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	26: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	25: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	24: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `<top (required)>'
	23: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `load'
	22: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/bin/database_consistency:44:in `<top (required)>'
	21: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency.rb:47:in `run'
	20: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	19: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	18: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `each'
	17: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	16: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	15: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	14: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	13: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	12: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	11: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	10: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 9: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 8: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 7: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 6: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 5: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 4: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 3: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
	 2: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:71:in `associated_key'
	 1: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:472:in `active_record_primary_key'
/Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:322:in `primary_key': [1mUnknown primary key for table favorites in model Favorite. ([1;4mActiveRecord::UnknownPrimaryKey[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	37: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
	36: from /Users/usman/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
	35: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	34: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	33: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	32: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
	31: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	30: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	29: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	28: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	27: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	26: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:476:in `exec'
	25: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	24: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	23: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	22: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `<top (required)>'
	21: from /Users/usman/.rbenv/versions/2.7.1/bin/database_consistency:23:in `load'
	20: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/bin/database_consistency:44:in `<top (required)>'
	19: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency.rb:47:in `run'
	18: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 3: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 2: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 1: from /Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
/Users/usman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/database_consistency-0.8.8/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:99:in `column': [1mAssociation (country) of class (Users::Customer) relies on field (id) of table (public.countries) but it is missing. ([1;4mDatabaseConsistency::Errors::MissingField[m[1m)[m
<===end===>
```

**Comment by djezzzl** [comment]
Hey @uxxman , thank you for reporting an issue. 

The issue is the following:
```
Unknown primary key for table favorites in model Favorite. (�[1;4mActiveRecord::UnknownPrimaryKey
```
Which means the model `Favorite` has no `primary key`.  Was it intentional in your project? 

In the meantime, I'll skip reporting such issues in the library.

**Comment by uxxman** [comment]
Hi @djezzzl, Thanks for looking into this.

Its of a joining table, so instead of indexing primary key along with the composite key and keeping two indexes, I just have

```ruby
add_index :favorites, [:customer_id, :offer_id], unique: true
```

**Comment by djezzzl** [comment]
Hey @uxxman,

I'm looking closely at all 3 cases of yours:

* 1 and 2 are about the same thing, some or your associations is broken because it requires to have `primary_key` on model `Favorite` but you don't have it in the schema. 
* 3 case is kind of the same (one association is broken): `Association (country) of class (Users::Customer) relies on field (id) of table (public.countries) but it is missing`. 

You probably don't see such problems day to day because those associations are never used by your code anymore but they are still there. 

So, what I'm planning to do is to improve the output of such issues so it becomes clear what needs to be done.

**Comment by uxxman** [comment]
> * 3 case is kind of the same (one association is broken): `Association (country) of class (Users::Customer) relies on field (id) of table (public.countries) but it is missing`

This is also a special case in which primary_key of the table is 'code' so instead of having 1,2,3 in Users:Customer I have DE,BE,NL.

```ruby
class Country < ApplicationRecord
  self.primary_key = :code
  ...
end
```

**Comment by djezzzl** [comment]
Are you saying that `Users::Customer.first.country` works just well, right? 
Could you please share then how the association is defined on `Users::Customer`?

**Comment by uxxman** [comment]
> Are you saying that `Users::Customer.first.country` works just well, right?

Yes 



> Could you please share then how the association is defined on `Users::Customer`?

```ruby
class Country < ApplicationRecord
  self.primary_key = :code
  ...
end

module Users
  class Customer < User
    belongs_to :country, foreign_key: :country_code
  end
end
```

The countries tables just maintains the list of supported country codes and in associations, instead of having an integer ID we use CountryCode, this way eliminates the need of loading countries when we want to show the country_code of an association.

**Comment by djezzzl** [comment]
Hey, could you please try `0.8.10` and say if you still  have any errors?

**Comment by djezzzl** [comment]
Feel free to reopen the issue if you still have.
