### ISSUE TITLE
Unhandled exception in ForeignKeyTypeChecker

### ISSUE THREAD

**Issue by bencallaway** [djezzzl/database_consistency#74]
I encountered a couple of errors when running the latest update of database_consistency

ruby 2.6.6p146
rails 5.2.4.4
database_consistency 0.8.9
postgresql 12.4

The errors pertain to associations from a table-backed model to two *view-backed* models
`Association (import_member) of class (ImportRow) relies on field (id) of table (import_members) but it is missing. (DatabaseConsistency::Errors::MissingField)`

Since the parent model is based on a view it is not possible to set a FK relationship. Although there may be some another constraint / consistency that I'm still lacking. Regardless, I'm not sure if this is a case that should be supported or handled, but in the spirit of the error message given I thought I would open an issue just to make sure.

Output `database_consistency_2020_11_18_17_20_21`
```
<===begin===>
[1mTraceback[m (most recent call last):
	37: from /Users/bencallaway/.gem/ruby/2.6.6/bin/bundle:23:in `<main>'
	36: from /Users/bencallaway/.gem/ruby/2.6.6/bin/bundle:23:in `load'
	35: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	34: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	33: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	32: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
	31: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	30: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
	29: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	28: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	27: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	26: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
	25: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
	24: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
	23: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
	22: from /Users/bencallaway/.gem/ruby/2.6.6/bin/database_consistency:23:in `<top (required)>'
	21: from /Users/bencallaway/.gem/ruby/2.6.6/bin/database_consistency:23:in `load'
	20: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/bin/database_consistency:44:in `<top (required)>'
	19: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency.rb:47:in `run'
	18: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 3: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 2: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 1: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
/Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:99:in `column': [1mAssociation (import_member) of class (ImportRow) relies on field (id) of table (import_members) but it is missing. ([1;4mDatabaseConsistency::Errors::MissingField[m[1m)[m
<===end===>
<===begin===>
[1mTraceback[m (most recent call last):
	37: from /Users/bencallaway/.gem/ruby/2.6.6/bin/bundle:23:in `<main>'
	36: from /Users/bencallaway/.gem/ruby/2.6.6/bin/bundle:23:in `load'
	35: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	34: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	33: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	32: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
	31: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	30: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
	29: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	28: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	27: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	26: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
	25: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
	24: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
	23: from /Users/bencallaway/.rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
	22: from /Users/bencallaway/.gem/ruby/2.6.6/bin/database_consistency:23:in `<top (required)>'
	21: from /Users/bencallaway/.gem/ruby/2.6.6/bin/database_consistency:23:in `load'
	20: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/bin/database_consistency:44:in `<top (required)>'
	19: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency.rb:47:in `run'
	18: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `reports'
	17: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `flat_map'
	16: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:12:in `each'
	15: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:13:in `block in reports'
	14: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/base_processor.rb:28:in `reports'
	13: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 3: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 2: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 1: from /Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
/Users/bencallaway/.gem/ruby/2.6.6/gems/database_consistency-0.8.9/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:99:in `column': [1mAssociation (import_table) of class (ImportRow) relies on field (id) of table (import_tables) but it is missing. ([1;4mDatabaseConsistency::Errors::MissingField[m[1m)[m
<===end===>

```

**Comment by djezzzl** [comment]
Hey @bencallaway , thank you for pointing this out! 

I'm not sure I understand the case, could you please share some more information, like:
- How `import_member` association is defined in class `ImportRow`
- Confirm if `ImportRow.first.import_member` works perfectly for you
- Show how `ImportRow` class table is defined on schema
- Show how `import_members` table is defined on schema

I'd very appreciate such information 👍

**Comment by djezzzl** [comment]
Im the meantime, could you please also try version `0.8.10`? Feel free to reopen the issue if still stays.

**Comment by bencallaway** [comment]
Thanks for the feedback and the fix @djezzzl. `0.8.10` did in fact fix my issue. It was on account of my using a custom private key `email` as opposed to `id` in this case. The fact that my associated models were based on database views was irrelevant after all. Working with `0.8.11` now, and it is running smoothly

**Comment by djezzzl** [comment]
So glad to hear that! 

BTW, feel free to suggest any features if you have any in your mind 👍
