### ISSUE TITLE
Issue with custom foreign key

### ISSUE THREAD

**Issue by mockdeep** [djezzzl/database_consistency#86]
`database_consistency` reports an error with one of our model relationships:

```rb
class FormRequest < ApplicationRecord
  # t.integer "status_id", null: false
  belongs_to :status, inverse_of: :form_requests, class_name: 'FormRequestStatus'
end

class FormRequestStatus < ApplicationRecord
  has_many :form_requests, inverse_of: :status
end
```

Error:

```
<===begin===>
Traceback (most recent call last):
	24: from /home/fletch/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
	23: from /home/fletch/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
	22: from /home/fletch/.rvm/gems/ruby-2.7.4/bin/database_consistency:23:in `<main>'
	21: from /home/fletch/.rvm/gems/ruby-2.7.4/bin/database_consistency:23:in `load'
	20: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/bin/database_consistency:44:in `<top (required)>'
	19: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency.rb:53:in `run'
	18: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/base_processor.rb:13:in `reports'
	17: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/base_processor.rb:13:in `flat_map'
	16: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/base_processor.rb:13:in `each'
	15: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/base_processor.rb:14:in `block in reports'
	14: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/base_processor.rb:29:in `reports'
	13: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:15:in `check'
	12: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:15:in `flat_map'
	11: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:15:in `each'
	10: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:18:in `block in check'
	 9: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:18:in `flat_map'
	 8: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:18:in `each'
	 7: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:19:in `block (2 levels) in check'
	 6: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:19:in `map'
	 5: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/processors/associations_processor.rb:21:in `block (3 levels) in check'
	 4: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/checkers/base_checker.rb:34:in `report_if_enabled?'
	 3: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/checkers/base_checker.rb:25:in `report'
	 2: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:40:in `check'
	 1: from /home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:85:in `associated_column'
/home/fletch/.rvm/gems/ruby-2.7.4/gems/database_consistency-1.1.1/lib/database_consistency/checkers/association_checkers/foreign_key_type_checker.rb:99:in `column': Association (form_requests) of class (FormRequestStatus) relies on field (form_request_status_id) of table (form_requests) but it is missing. (DatabaseConsistency::Errors::MissingField)
<===end===>
```

Happy to provide any additional information that might help debugging. These models are heavily used in our application, so I'm confident they are working.

**Comment by djezzzl** [comment]
Hi @mockdeep, thank you for reporting the issue! 

Could you please show what SQL query outputs the following command in console for you? Also, please share if that is working as expected by you.

```
FormRequestStatus.first.form_requests
```

**Comment by mockdeep** [comment]
Ah, nevermind! We don't use the inverse relationship, so that didn't work. It should have been:

```rb
class FormRequestStatus < ApplicationRecord
  has_many :form_requests, inverse_of: :status, foreign_key: :status_id
end
```

**Comment by djezzzl** [comment]
> It should have been:

Yes, that's what the error was about =)
